app:
  wechatToken:
  openAIModel: text-davinci-002
  openAIUser: ricky
  openAIToken: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6Ik1UaEVOVUpHTkVNMVFURTRNMEZCTWpkQ05UZzVNRFUxUlRVd1FVSkRNRU13UmtGRVFrRXpSZyJ9.eyJodHRwczovL2FwaS5vcGVuYWkuY29tL3Byb2ZpbGUiOnsiZW1haWwiOiI4Mzg3ODgyNDBAcXEuY29tIiwiZW1haWxfdmVyaWZpZWQiOnRydWUsImdlb2lwX2NvdW50cnkiOiJVUyJ9LCJodHRwczovL2FwaS5vcGVuYWkuY29tL2F1dGgiOnsidXNlcl9pZCI6InVzZXItd2Z1ZEpXWHJXQ3docFhuTTNYUnQ0RklUIn0sImlzcyI6Imh0dHBzOi8vYXV0aDAub3BlbmFpLmNvbS8iLCJzdWIiOiJhdXRoMHw2M2UxYzFhZTAxNzY1NDdhY2RmZGI3ZTQiLCJhdWQiOlsiaHR0cHM6Ly9hcGkub3BlbmFpLmNvbS92MSIsImh0dHBzOi8vb3BlbmFpLm9wZW5haS5hdXRoMGFwcC5jb20vdXNlcmluZm8iXSwiaWF0IjoxNjc1OTIwNzU2LCJleHAiOjE2NzcxMzAzNTYsImF6cCI6IlRkSkljYmUxNldvVEh0Tjk1bnl5d2g1RTR5T282SXRHIiwic2NvcGUiOiJvcGVuaWQgcHJvZmlsZSBlbWFpbCBtb2RlbC5yZWFkIG1vZGVsLnJlcXVlc3Qgb3JnYW5pemF0aW9uLnJlYWQgb2ZmbGluZV9hY2Nlc3MifQ.O-UCCCT2r3uohCumt_sga1LLq23Vk-9kU37BD4QCZ1cIOugZAR39OUFOwBM8XUbYYqEOchGszVrVf_h2LUjty2Ma0lBUoni-PuvE_B8PBaN2V8Zgia1Hua1f2aMYeNYr3UA12DjJeKmPo_w-R3vtYaYE_Yd1ltwYTx6QGimsEu-wFafZ9YpmUKkSXhUML6uNtJYmNmHJwdJxgD2TJEFWdGWPbgrfqdpzvDUMnS4eN_1gMkXLD0HGPPwF3X-ahQxUtlqC4O9xkbYz7J9C-s-GWg15fBrhVRmEhqj2yVphHuNKhlKUWZ9ZQggOwiIdOBz2e_q36v0N2mjoVdm4fy-heg
  gptMaxTokens: 3000
server:
  compression:
    enabled: true
    min-response-size: 1
  tomcat:
    connection-timeout: 60000
    uri-encoding: UTF-8
  servlet:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
      force-response: true

