app:
  wechatToken: 336C6E655D810D4C15BC8B06922AD9C7
  openAIModel: text-davinci-003
  openAIUser: ricky
  openAIToken: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6Ik1UaEVOVUpHTkVNMVFURTRNMEZCTWpkQ05UZzVNRFUxUlRVd1FVSkRNRU13UmtGRVFrRXpSZyJ9.eyJodHRwczovL2FwaS5vcGVuYWkuY29tL3Byb2ZpbGUiOnsiZW1haWwiOiI4Mzg3ODgyNDBAcXEuY29tIiwiZW1haWxfdmVyaWZpZWQiOnRydWV9LCJodHRwczovL2FwaS5vcGVuYWkuY29tL2F1dGgiOnsidXNlcl9pZCI6InVzZXItd2Z1ZEpXWHJXQ3docFhuTTNYUnQ0RklUIn0sImlzcyI6Imh0dHBzOi8vYXV0aDAub3BlbmFpLmNvbS8iLCJzdWIiOiJhdXRoMHw2M2UxYzFhZTAxNzY1NDdhY2RmZGI3ZTQiLCJhdWQiOlsiaHR0cHM6Ly9hcGkub3BlbmFpLmNvbS92MSIsImh0dHBzOi8vb3BlbmFpLm9wZW5haS5hdXRoMGFwcC5jb20vdXNlcmluZm8iXSwiaWF0IjoxNjgwMzU2MjQ0LCJleHAiOjE2ODE1NjU4NDQsImF6cCI6IlRkSkljYmUxNldvVEh0Tjk1bnl5d2g1RTR5T282SXRHIiwic2NvcGUiOiJvcGVuaWQgcHJvZmlsZSBlbWFpbCBtb2RlbC5yZWFkIG1vZGVsLnJlcXVlc3Qgb3JnYW5pemF0aW9uLnJlYWQgb2ZmbGluZV9hY2Nlc3MifQ.zUFIxxCpSWf-Laj7MSmJB9N-gKinwGmGrV-67ftCMht4nWfDwB2SEx05KN34tNwZz_gZ3Zscwj4imDOdFCFAcLnKwWzOgYcP93X6BN7xKq0Kj-ETp4EkrcBVUj14G5KHHDjby-8k33FlUuei1P1wzalLmUAwxieZIcT1URAjB0IxtJEwgB9nJijNEk4DYkIS3GIFdFttVyZe1A9yQcZ1h70Eq10i5cwQ00IeQY1R8NfXAXVZ_67U0OmFVUgFI2lminEwGROfDfHnhOurtIu-_Vm_FH-7hKztZEv7xWSyDzi4vweoMmzHnA4-KhCriko4dxIla9649jBjTNxvh1jFUA
  gptMaxTokens: 1000
  openAITemperature: 0.9
  openAITimeout: 60

server:
  compression:
    enabled: true
    min-response-size: 1
  tomcat:
    connection-timeout: 30000
    uri-encoding: UTF-8
  servlet:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
      force-response: true

cache-config:
  # 过期时间
  expire-time: 90
  # 缓存最大数量
  max-size: 500